# Generated by Django 4.2.3 on 2023-07-19 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0002_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Thing',
        ),
    ]
